apiVersion: v1
kind: Secret
metadata:
    name: dummy-sops-secret
    namespace: default
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:OBmwj4gEGr+z+uvEyQjHZwogmzjqOVI=,iv:FlF50EqUTWBPgRK2Fea7mZlfdQo3DPt+c3UMB3LS52I=,tag:3uWWrFB9lu5+8UFzVI1ZWw==,type:str]
sops:
    age:
        - recipient: age1vk7c2yw7dmmk62vwpns5m8z0ljujkf9xv8ad8ml5qxp97l7mlatq0mq9lf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKMkl6cWhFVTZPOW5TQ0dK
            NnlDaTFxMzl0eStwd210d3NNSGRFWjBPQ0c4CjVZSS9HSHl3ZUQvbTJRUzNyUTda
            TE9yYldLNWhYTW9ZTExkNHhVKy9CZE0KLS0tIFE0MHJHMUlnT1dHcGVEWUhpK0VR
            YVIvNUFhVDNHM1I4bHVlajlaRzBLOWcKxQPzeaAMgeBkwjZ7JVKhyqLYxTxhY/Tj
            7Dv89mfn8PCLHf2MV85QmjKjmReLuaTTfPtbxJSmVC15pK4N8u0PGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-01T18:21:16Z"
    mac: ENC[AES256_GCM,data:aC3PIfeMm344/b7YqfUwrKjDXclvoQ09EbKde2YxFbEjB8shUFME7uqfLlFJXDQio3P8vhrsfzk+M5KvTDWNOvKOsGmp+JoWHSQFyw0D+VE21+EuO9AWFvAKy69ZDDBSHeqKqBmd0ZagPbNy0MOf0Nokb5OPC5Ap74fRpoW/B8I=,iv:JdCfCtET4LvRJNwGTCO4dqtjxa03j9NzeWbqNNXJgAY=,tag:J8G4eT0JiaXereL4yI9jYA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
