apiVersion: v1
kind: Secret
metadata:
    name: apply-agent-postgres-backup-r2
    namespace: apply-agent
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:1IzUYjc0/jCRft5D0BN7lSfnP6Y5PRPV,iv:0dHwN34QmtZC7cx7cA85/UQBtnU7jm8p7Gis42Hve2Y=,tag:+Fddv+DECHM2E+0Ls9xM8g==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:gqYx/LYxof1BXKPp3UmJCjNpMKfm9zbuthUVYA==,iv:VnZQqQdT5QFUnVlOko6SaXYzJ3f6D6TklElb9YGfyqg=,tag:Dts7aKJwaexxlhn3XySvgw==,type:str]
sops:
    age:
        - recipient: age1vk7c2yw7dmmk62vwpns5m8z0ljujkf9xv8ad8ml5qxp97l7mlatq0mq9lf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDMmN3NFgzc0FYY2I3TzRG
            Z1o5OVlrU1hqTzVzbVVHbmRwVkkyKzUwRUg4Ckk5Mk1sTDBCa0dUa0c2Uld2enIw
            YXB6eFBCK2R2ZTJOdE9JNWQxZHVCUlEKLS0tIDU0Z1BaOU5hd3c2VWtmZ2x2V0Jv
            R29TZTI0azZ4aE5jVnNLZldBQzBhdlEKhCNrckdCfbuMlsx7jcdcJs/US0Qxz9jS
            /fhbaI2qXLCzt4id7hcTE9ZyAEbJSeu7PZhjqN0dvK7nhNaMd2Yskg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-01T19:22:20Z"
    mac: ENC[AES256_GCM,data:e/yqSe2CBwmc2PqqYLvbMUgr9skbqvJjUgVa7sK0dewORqkulFTtJInn2Y/TA3T9jjuKLuZ/i04LaEVq8tArA6X/AOwxdkuWZBjD9n//9IAPjGZIsAdQNdC7PSSxTxTSgacBj7oRw3ulfwrLkZ8t1+dHXoDwaZsk7yKyufz/XDI=,iv:czt3mvqWuDaJDeBpNycn1YEYtX444F0sdBEMMd1Ujtk=,tag:JW9pqb9aDFJx1/mGr8RFYQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
