apiVersion: v1
kind: Secret
metadata:
    name: apply-agent-secret
    namespace: apply-agent
    labels:
        app.kubernetes.io/name: apply-agent
        app.kubernetes.io/component: secret
type: Opaque
stringData:
    DB_USER: ENC[AES256_GCM,data:LCiAt6HjHHvFkw==,iv:yN8xH7ZRgOyOELmc7mjIMNknD0Y2A1hKyz1YhGlyrZY=,tag:HISMSQEZukuo7GkGJYyUcQ==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:r0/fIXT7nRXoKJCMsPZ3I9ezwy9YRzNRl+Yku+DPOBBTSuw0egBcWHgSmw==,iv:sF+JW0sP6YbOOuGoXztfvA27/tZCAk0+JF1Xr3hvB+U=,tag:8QR3VBYt3C7f7vEPop+G5Q==,type:str]
    username: ENC[AES256_GCM,data:/383iMNZS7aUwA==,iv:nZfBBjDXcAcy6XoO2hmonTzzXTVdfFbpzOtsmFsbyjw=,tag:vSjBAmzD+jLYLSVOfx3PKw==,type:str]
    password: ENC[AES256_GCM,data:g1rOByUMzWU2rmLfx1ZwVbWIJXl8yCXJC4g48AphVw7Qc20R+czWx9ld1g==,iv:BqCn2MsvInwDvjU29CQWmuiwDGJ1rlPGnVqpwRv0TME=,tag:k4GnZUVKXwFk4T9My2sHWA==,type:str]
    VAULT_PASSWORD: ENC[AES256_GCM,data:Jv1qxHxVTRdh3sYH40H5iLZvwfnL1MYpxpiVkQEwWGGUEbaKLKXrHO/lmtIjP9WpuAoKn6LUHkwiHUD9EX+WbA==,iv:xe58OZVMtXrjDHJCm9coFNfLvMkJyIqQCOzu1zLScKA=,tag:K23ReffdX6nVg7jViCTBBw==,type:str]
    PROTON_BRIDGE_USERNAME: ""
    PROTON_BRIDGE_PASSWORD: ""
    API_SECRET_KEY: ENC[AES256_GCM,data:dZ9M83jZ2rTkXkMXLvC/iKmUDHApPIyeY2Y3r6ldW4asxEQ9dhoqlQ3IKAtbZil/5aOpuFuEsB6ooxhfieTNzQ==,iv:j2+SH8rzNiSjkJLGdUbDcndTMja4q1FpErhO7QpSuBs=,tag:gGJLXFyAnjXhH+qdxbuQhw==,type:str]
sops:
    age:
        - recipient: age1vk7c2yw7dmmk62vwpns5m8z0ljujkf9xv8ad8ml5qxp97l7mlatq0mq9lf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqN1pPN1Qwdms1L3N0bks0
            LzY5SWJGS1R0LzFWdGVJdG80alZZVmlGdHdJCnhwanJMOGZXelo2akpBdEZ4ZThm
            cTEyOUFhUzV2TDRZTFFlNHloQWZ0UkkKLS0tIHJ0ekN0ZFpDUFRKOXdYaW5MWW5I
            UG9zUnUyekpSTWdYRjVsWlVpWEJyd3MKKLIgJzcO3FQ4B8Cx4GXGoJmMW/LDdG4x
            DLIm2jFH+d7VddnBrnXG/7HjMjeJI9Ub+SuoVApgAE2qLbmSC7FGqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-01T21:09:25Z"
    mac: ENC[AES256_GCM,data:VfmkJF9QT6hB1uvOH2RAklwRxt4NbLtZfihylzzLESG2vZh2IG5ztsm08dwVYSO2vsisnn78s+hbyo/zopojdcHQmEbc4MBNeIspXoJqLkR9FpttvdhbKMTMH0Kms0P9OjmsSWrT5XtmGRtq9KbHgZUptt8gOThQQENDdoXTs68=,iv:FG6F+L+mPVY3FiUR/Fq9hlWpr9cJouW2/YP5BDbW2bc=,tag:bDkCNHGfYcQINvS4HFI1Pw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
