apiVersion: v1
kind: Secret
metadata:
    name: ghcr-pull-secret
    namespace: apply-agent
    labels:
        app.kubernetes.io/name: apply-agent
        app.kubernetes.io/component: image-pull
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:of0RIr8X1+CZnR9/dj6YYFtUYxPfqnR5pGwf7EvQjNkNwzisARczoKjdnzXKilKR8CgfvabSopq1HwqvoxcvX4666HCRF+IdfpAcvWIYMOvDqZnp92rSbHewT/mal0QK63yldDVa9mnW+z/wPGnURLP+SkdYtWuSwI/vJQ12c3gKf7QJqStp12Ty44KZGVLsVECu/LTSeAw+ww7iEqCq/LVSYTN7l99nAJGWOPsGP+HmZPm02+Fy5X0P,iv:5zLZO0uxjH0Ge27JZXhvPiU92VXnqG0b8cnwi4EGn9Q=,tag:w8BHmSP+IZX8XRGOTCUdqA==,type:str]
sops:
    age:
        - recipient: age1vk7c2yw7dmmk62vwpns5m8z0ljujkf9xv8ad8ml5qxp97l7mlatq0mq9lf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwc1ZVWlAzUEZHRTVUaUdD
            QU9TY1JUYmxNRWpjVHI1MkRJdkRCRXJwbXdvCm5mTXlZNXd5YUp2MFpQcmwzUWsr
            V0pUVjlHdFJ5eER4ZG5SMXBaWHVpNk0KLS0tIFlVSi9RNkdtMzBXeFdtODRmVmVM
            ZE5JUG5CWnVQbDYrQkVFU0NFUEx4ZG8KNooGoEwQ5rXZ8n3HaacRQPS+jrerfW73
            7co8bW92jl6sCOcVuf/OzuL/cw02xGeE3EX+lbZoxNACm1mQWJzkuQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-01T20:44:54Z"
    mac: ENC[AES256_GCM,data:gYOL4Nk9dtjpyEBwkMZEsmyWAMZkdq4qCH627kWXfU63IQbiI4UCQ2i9V/nPn8FwWIw8AG9ifXbdqS3Okys+qdPhG40Z0knpnr+16wg/YhAWN2qJQVlue5pgrTa76FmbgukZZPpklZy8qgq8KdpjaqCxB/O4PUe/Be+kf5guL6s=,iv:eVyi1rJke75M3k+nvfxR+A7MzLrX4fqJQeJhRD0GOxE=,tag:vs6bBXCzKE3qNokFvfTtMQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
