apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apply-agent

resources:
  - namespace.yaml
  - configmap.yaml
  - pvc.yaml
  - proton-pvc.yaml
  - db.yaml
  - scheduled-backup.yaml
  - deployment-api.yaml
  - deployment-web.yaml
  - deployment-worker.yaml
  - service-api.yaml
  - service-web.yaml
  - networkpolicy.yaml
  - ingress-tailscale.yaml
