apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: proton-bridge-data
  namespace: apply-agent
  labels:
    app.kubernetes.io/name: apply-agent
    app.kubernetes.io/component: bridge
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
