apiVersion: v1
kind: Service
metadata:
  name: cozy-friends-approval-api
  namespace: cozy-friends-site
  labels:
    app.kubernetes.io/name: cozy-friends-approval-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: cozy-friends
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: cozy-friends-approval-api
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
