apiVersion: v1
kind: Secret
metadata:
    name: cozy-friends-approval-secrets
    namespace: cozy-friends-site
type: Opaque
stringData:
    admin-token: ENC[AES256_GCM,data:ZSEFjhQkavC26NrBRiZRX19xyWuc9ZKULbAm/5lwlxtdMiG2cq6cbrf/u38Bos55G6wmPYBP1q4vpW4NDZgy/w==,iv:nOH1DV5D7NjmmpCtWoaKnQFbgSoO9gq8EDVY6jDrTpE=,tag:oIjb5ER0E8HVUYpfEuKAQg==,type:str]
    sync-token: ENC[AES256_GCM,data:epdYpjdEcYztmjWtU9DS/SJmRv7hBcce8ctKLMK0gnV343jffO1sbfxrC2pKvFkT4/Dzo7ucHAcaTNtazMdzkg==,iv:a+FXVVx+XX+eBo+UFeevhmBPXcoBKnd9x15BfwkmQhk=,tag:rvgMFOkXQA1r9BgGkD8FPQ==,type:str]
sops:
    age:
        - recipient: age1vk7c2yw7dmmk62vwpns5m8z0ljujkf9xv8ad8ml5qxp97l7mlatq0mq9lf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYTzE1eGlrTENqRVBxdC85
            ck8rellWN0x1bS9XanhCWkM4UGI4M2F5UDF3CjRVV3dGLy8wT0kwQ0UzRGFTeVlz
            V1lRanBLSEdrU1FYMEVieGdMZTJieWMKLS0tIFZReWZaaTFadUM4U01uZk9tQjA0
            dWlEWUNNRVhkZSsvS0hNWHVuL0hyYlUK6oee+Y99Vi4CxiohAnIcOdj1/oq967Lu
            sNGvOHn0DT/SFyoEsWPvFtIP6G4PlM1NmYO+S6s/aWRg5J5Pk8sfNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-11T08:05:42Z"
    mac: ENC[AES256_GCM,data:AyPB/PNMY8X0sZPmgDO+No1uDGnhk1Pfae1ruzo4j3/cmDUuOfr3Hoo0Bav2577OqrAJGnjFwId42eQq4pDZXb2j8IgFHDDhqh79OIsHr3JIm+BziIj1jNApIJewCAj+2EZ1tQDs0k1PdTy6Re6Pgt+orJ+zJFgQAGUo/VCIyFQ=,iv:i8P0MIJ+UcX5befgfQU9OBic1Hy9383KsCORxQd3O1A=,tag:PJi6axsebZK0kTnbMo+PEQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
