apiVersion: v1
kind: Secret
metadata:
    name: cozy-friends-approval-secrets
    namespace: cozy-friends-site
type: Opaque
stringData:
    admin-token: ENC[AES256_GCM,data:ZSEFjhQkavC26NrBRiZRX19xyWuc9ZKULbAm/5lwlxtdMiG2cq6cbrf/u38Bos55G6wmPYBP1q4vpW4NDZgy/w==,iv:nOH1DV5D7NjmmpCtWoaKnQFbgSoO9gq8EDVY6jDrTpE=,tag:oIjb5ER0E8HVUYpfEuKAQg==,type:str]
    sync-token: ENC[AES256_GCM,data:epdYpjdEcYztmjWtU9DS/SJmRv7hBcce8ctKLMK0gnV343jffO1sbfxrC2pKvFkT4/Dzo7ucHAcaTNtazMdzkg==,iv:a+FXVVx+XX+eBo+UFeevhmBPXcoBKnd9x15BfwkmQhk=,tag:rvgMFOkXQA1r9BgGkD8FPQ==,type:str]
    turnstile-secret-key: ENC[AES256_GCM,data:9keUBSi/Gud757Q2cKD+4Vm6hDqd97MsuOnThrPUk13nszA=,iv:ii3Z43BLE7FV18k1fIAQqzHVPlOKduxrD5ZJ6eMnGd8=,tag:rlS5OQMIOGmcsqlL8nLWMw==,type:str]
sops:
    age:
        - recipient: age1vk7c2yw7dmmk62vwpns5m8z0ljujkf9xv8ad8ml5qxp97l7mlatq0mq9lf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYTzE1eGlrTENqRVBxdC85
            ck8rellWN0x1bS9XanhCWkM4UGI4M2F5UDF3CjRVV3dGLy8wT0kwQ0UzRGFTeVlz
            V1lRanBLSEdrU1FYMEVieGdMZTJieWMKLS0tIFZReWZaaTFadUM4U01uZk9tQjA0
            dWlEWUNNRVhkZSsvS0hNWHVuL0hyYlUK6oee+Y99Vi4CxiohAnIcOdj1/oq967Lu
            sNGvOHn0DT/SFyoEsWPvFtIP6G4PlM1NmYO+S6s/aWRg5J5Pk8sfNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-11T08:57:02Z"
    mac: ENC[AES256_GCM,data:GmuFC5yh0S9IMHe7kjI+8oAHhrdOGfm3Y4k/F8X5WtISpOANoe98kze4T9rmxMtn8Jy5+YEIC21JFADOXN5LRlkPjzQJZOel8zzB6/f9Qb3JeXTICEQlCJKWC2MNwew9l9rTzx20pGziU1zhJ+Q4yu8Wu9dg7h4WQQUKFkeKKXU=,iv:r0S+NdYfJku0/uXPdOM57tJENjMCkqLgjckRpTcDhWQ=,tag:qEuye5H/tTIgY2oCLwozzA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
