apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cozy-friends-site

resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - networkpolicy.yaml
  - approval-db.yaml
  - approval-api-deployment.yaml
  - approval-api-service.yaml
  - approval-networkpolicy.yaml
