apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-telegram
    namespace: monitoring
type: Opaque
stringData:
    bot-token: ENC[AES256_GCM,data:bKuTG2lWPH5aSNfSEznyVNl/Hd5RKOt2jE2MqaOocn6ypiUN0fjn7UtLQq0IFA==,iv:WXaAHwlCk3EpndBfXKn8D8eJkJsemmGX23CanrLqvAc=,tag:TOrl0VTeK7EuIqshT2jM5A==,type:str]
sops:
    age:
        - recipient: age1vk7c2yw7dmmk62vwpns5m8z0ljujkf9xv8ad8ml5qxp97l7mlatq0mq9lf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKU1V1TGlISWd4c2R5bGh0
            SmdUcnlVazJwbFg0eWZ2UDY3N3lJRTA1eDNvCk1BK3dmeTJybkdiWmFFTHdJWlZQ
            ZC96ODRvZ3ZGUFFlMEpwSVQ3Z25sY2sKLS0tIFlkYkEyV05vWlIvMDVSSWlINks5
            STJFelEvdVRoYUM1ZE93aFlucjJ4RncKf9dbl1oMqCnQzAvwCcL5/W7e9LU2H0hN
            uQ6eARno4+GIMCy8AvZHoYxK2QM/L3++NA7b3Sex9/KMdBvfD/MRLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-01T18:47:13Z"
    mac: ENC[AES256_GCM,data:uTJbY8Ia9JCG7V60H7h8+woLrgwPwsxZRcwmvwWv+wr58djTw00beQW9YNFiqT5eprZotI8uz2KBA6e0HCbrcydNdQqrGUbGO1wZtEpr85F1KOako0dFf5Va2+twK5sgWrFfgmXLmIIaDdAdo2ZBPGnzjqlkjGY7y3j437iJBls=,iv:RWR+hs3cqHcz5Op7NnTu1l6q8Bt3qrlN0EHZHMcwHow=,tag:rg6xwkKi90ezdNrUQ1e0Xg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
