apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel-token
    namespace: cloudflare
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:TffcgXXZKS5oAxApDqX2ALut8i9EQj+1KLc401+gY0YfxwhuHsf9cNUvIgFf4XaelyM0OypiE0y4vUC/Jha8/XVkXjp2irwgG8LYXEbKOLGI9q7/nhrOg6kSza9uPgjxCyf56/vV6fWE6EwfLVhQQdo2/S7b9qnWKVqRgND7XacEr85Qo/hK5KuphSUOoZnIPmbnFJpR/ywHghYLn+Gc+B8gM7ZQEOclmJOJO8T5qPa6+y4tbbcxXJEcZzM67QZ2+tMtc4tlryFHsHzCp2eonXJyzHjP9x1zx20tUgTCI4q4IUE5jo8h3k9iEVC2cy8FzD3sVduIk2U=,iv:BDMLaABDBr7w4fZriV0ivKC7p8hicwfZNPCz6WE0ERY=,tag:S4RFvVTLOAmFmB1T5Uaj0g==,type:str]
sops:
    age:
        - recipient: age1vk7c2yw7dmmk62vwpns5m8z0ljujkf9xv8ad8ml5qxp97l7mlatq0mq9lf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0VUJZOGlRUldhaldSWjN2
            VlFpeXdiemloZ0o5bVhVRzI3MExRM0R4cXhFClB4QWdDeVljbW9Fd3RjcnNJSG9r
            NnhwVERWQlZwU2FpdUxTMi9HQ0U1UkkKLS0tIG5zc2lncVdzZ2NKRVcraFJrbzdL
            VlllMlNJUm8reDFCRWdadVNCb25DSWMKI1rkiLt3v5BfZgKbBb/9v5pPxIh+2M/+
            hXY8pVLkJa9R0QoAguaVEjWl0HBKW370c3MyM4IZIygKjjVv7tLgZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-20T16:21:38Z"
    mac: ENC[AES256_GCM,data:ZfKNbAa37puUKjrYo+1X+ZZ8sj5+cJcz7SWLzUybFVLncLH33b/0flwXV+i4foSi7S1C7wTN+3brrv5cQiq8u8tEiptB4hEZDcJwhUEmBSQq/M2fFxzqdI02OTC1YE4BZHhGiMnTvSHYwjgTYaYga7PCtI2BTDfBt6/5leNTTMQ=,iv:nUrlYQs/YyIAIx8QCjg8WsIcdCHZe//ONIszM7pezQQ=,tag:qbtleuMSay6+RLY9Duj6xg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
