apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel-token
    namespace: cloudflare
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:ArnTF+7GQIYqVghRvRQH2/G1iKholCH757gvS1tjZss4A6BVnKwveNPB0HQeawfG6Vj3sadyeKv4s+44fYDpHp9sPHOWQQE8EI4PsSU8tZHuRcKvtE29jaCtnblkMkGxmz9lO4HiHr2cr80N0sLQhaM0w0VVzkPdNt77w86vVhYhmxPrVaSqB4pCuaAb89ucjvRzheclJKmnVKigZ5B3ZJJ9WFS1BdPEybt1ETBIqZ74t2603EOc9w==,iv:90EtqSIDF3dpmcuhQL061ME7DQQwKXAUkbbIatMupd0=,tag:X2a2NOIEJnPR3f0Qag14Hw==,type:str]
sops:
    age:
        - recipient: age1vk7c2yw7dmmk62vwpns5m8z0ljujkf9xv8ad8ml5qxp97l7mlatq0mq9lf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0VUJZOGlRUldhaldSWjN2
            VlFpeXdiemloZ0o5bVhVRzI3MExRM0R4cXhFClB4QWdDeVljbW9Fd3RjcnNJSG9r
            NnhwVERWQlZwU2FpdUxTMi9HQ0U1UkkKLS0tIG5zc2lncVdzZ2NKRVcraFJrbzdL
            VlllMlNJUm8reDFCRWdadVNCb25DSWMKI1rkiLt3v5BfZgKbBb/9v5pPxIh+2M/+
            hXY8pVLkJa9R0QoAguaVEjWl0HBKW370c3MyM4IZIygKjjVv7tLgZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-01T19:00:06Z"
    mac: ENC[AES256_GCM,data:dGsJij6zQEwO0Mxbv8lJz+9xwgJgULnDmkWjBHf434r6j8YWcfi5a62puJjTKHV2sRlIO/AiJBf1JYRZUgrYtygImiUUAdL48Csxv7ENLmnblCUtl0Ntzf/xAD5aEFtrpjOTNjQsVsdQuDfosTriEVhG70vsFGfENu1+2BL+wpU=,iv:lgRu+8T2/mZKphiGTAs2fqPi2nQoLMExd79CpDZBHRg=,tag:e05J3S1I/Rs3FKt5wXjwdg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
