apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel-token
    namespace: cloudflare
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:KtjvWqAnHVoA7Ro+8p/IiilkoD4lQS8QTRnJoVanaNpTP1PfMyw29zn7g9XSB4FroGhKK58TP2ABpidSfPvdrMoR6oKIzlX6QESj0JHx1Zawsn7j9DtXYMnmbpy4pmBKseJL1GIZbSdArYKZJWgzomFh0Lp4g3FM/eDqFnwV6dCxHoS+EPzRpbEXBUsVrR6CqIpwic6cdcRmkig1crZEd/ZGul8IuiDG3/hVd289rnd+97FzxvSmTE48aShj5Lar7Uxm1RKGmvMoHd9pmej17CkbpGLVgvZx+I3sZmfpmVriWXJGsEYezBVqyP5fVvbt3Zfo1Fi4RFc=,iv:qDyel8+/hFnQjpXFlsi4rnwduQIrZwf/ObOS6OFCCH8=,tag:+rSOtVDPMGXoGlYS0HP3vA==,type:str]
sops:
    age:
        - recipient: age1vk7c2yw7dmmk62vwpns5m8z0ljujkf9xv8ad8ml5qxp97l7mlatq0mq9lf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0VUJZOGlRUldhaldSWjN2
            VlFpeXdiemloZ0o5bVhVRzI3MExRM0R4cXhFClB4QWdDeVljbW9Fd3RjcnNJSG9r
            NnhwVERWQlZwU2FpdUxTMi9HQ0U1UkkKLS0tIG5zc2lncVdzZ2NKRVcraFJrbzdL
            VlllMlNJUm8reDFCRWdadVNCb25DSWMKI1rkiLt3v5BfZgKbBb/9v5pPxIh+2M/+
            hXY8pVLkJa9R0QoAguaVEjWl0HBKW370c3MyM4IZIygKjjVv7tLgZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-02T19:27:14Z"
    mac: ENC[AES256_GCM,data:n10rzIUnHMD/phrjwo2fuOvUu0fEHwMEUw1y94aFrfKM5jsgjdmFDFgpofDokGFevzTh3XIkk52GYtPxPSuZaHlLKnrq/KrUjbLnDAXYHUFhqFozwfk2SRyuVwrXZZUdLceiQi9eoM2vxXE5eTxJYjmajry/RmifvxMUV2AZfRw=,iv:a6DRG4+nHlouFGumxL9MiMAIBrqyjC3Oanxj7f/t5os=,tag:DIf9JWYwyAPI5p7DjC31jQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
