apiVersion: v1
kind: Secret
metadata:
    name: longhorn-backup-target
    namespace: longhorn-system
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:JtafuGMkKXK9BdC2gSX8WNIWEQx2a8wasH49Oa2GRQw=,iv:sClBtMVHWm4ncYv7rjEaXZsPh/VWF/bIzobQUgVxips=,tag:94kH/ikzNlnZlufefPHAtw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:2JdQqGBnrCZB5ssqK6uVTx4hOhGC7QNhZcZO3pNp1Wiqsv05gAigVK/zCFKpAKtES3qPbPrjf/ii2XebyICoDg==,iv:UwygG4RuC47P4tDBGJ9MGhobexTd799g4HU0G5th8U4=,tag:PVzylmg3fX4VdiUh/16urw==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:Nfof5XEO3+jlId9FYPEfMvIBjAsC6Ui7Y9Yamsy2ewDSuDrlt6e4ZzpGitiNR1qhefBPueeQlnN+G3pOt/OMclo=,iv:KRdLHJ0Wh7Vz7/4UAjBOBDODsY9hJ9dDxgCNfIbRNq0=,tag:RkIG+1X9eb42dugBw5Thjw==,type:str]
sops:
    age:
        - recipient: age1vk7c2yw7dmmk62vwpns5m8z0ljujkf9xv8ad8ml5qxp97l7mlatq0mq9lf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3UWViZVNjaWU1aEFFZkJD
            cS8zUk1sL1ZNTGZvQUpqZHlQSlhYMnprL1JrCi9CeGpBVk55RllNRWVZUzlJUFRU
            RHVrbkd2dnBiQnBINWV5THJjOFNwQ28KLS0tIDFFSUhaVldQNVdhemlFVnR0YnJm
            eU55TlJ1bW9vcDArc2FjcXFjdGZ6b1UKTbnV678LtAJwkaOOlY0sGfOSC1ZA4V+M
            6ShZ7y8YVuLf49y/WTUS+DDO6fMy+kLwkJBNhYrUfHDzo+6gx51QBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-12T02:25:36Z"
    mac: ENC[AES256_GCM,data:RN7Zwefjl3b72EtSVWxojmc76Z1CK80n9v41AR2K9NWjCwyzCf1EalsAn9AMI3MxJynjqmNKinsUxakLNYbo2X/FJmPaFR/Uek+KRW5mhpDxtrR/EIRN9XrXDwlmzTAE6U+o+mY1cRCZTLuTqBk02IUYsshv3SNDDTMhJFWNMCU=,iv:T3MFNPrj4h48txZyEdVVuYW6JORcw0Yk1K3LIlUant0=,tag:WNFoVliFJuXe0H+8G3ixCw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
