apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: company-brain-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/danieljcheung/talos-kubernetes-homelab.git
    targetRevision: HEAD
    path: manifests/company-brain-app
  destination:
    server: https://kubernetes.default.svc
    namespace: company-brain
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
