apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cozy-friends-site
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/danieljcheung/talos-kubernetes-homelab.git
    targetRevision: HEAD
    path: manifests/cozy-friends-site
  destination:
    server: https://kubernetes.default.svc
    namespace: cozy-friends-site
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
