apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-config
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/danieljcheung/talos-kubernetes-homelab.git
    targetRevision: HEAD
    path: manifests/longhorn/config
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
