apiVersion: v1
kind: Secret
metadata:
    name: cozy-friends-secrets
    namespace: cozy-friends
type: Opaque
stringData:
    rcon-password: ENC[AES256_GCM,data:ldpimsxr7+S7esXrTF0Z5nV5riGouzLD+tG4BI1TthGnQuE0IGtfo0Ry/Mjj7E9a,iv:oz/AlXXV+dIpPR/ibqcAQki+h4aORKAKHtoojifeUto=,tag:50kPzFEE08KImuafvAfXwA==,type:str]
    restic-password: ENC[AES256_GCM,data:FWhOknr+Wvihf9zdp4IDcQ6J80GBYWdSxWkWCtxrUUxBHOh+bmPX4nljgA1irjkDPodoj1az31k7Gi/QbRCkGQ==,iv:cYiv0VXnksjEJvBpM9y4gliSpLOcjJn+4jt5K/AoPno=,tag:FLlutlla7ciXzbAF2oW5nw==,type:str]
    restic-repository: ENC[AES256_GCM,data:rxsntETWnCIlc5hoPYugVRWWkG/Iv4F2WPqxf+wH4RBn5mi75F2k0YLqwLus/Rbh5qUpxd9nc152YRu/LoYjw1+LzrTIo5mKBdk7xxitlDD/IJS3cjmGUMU=,iv:p39ijKUCU0OyzqNeW3vTXs+5yd/uNfe6vFkp/tdhjmo=,tag:Is3kuH6IBBvRRJKD8uUYnQ==,type:str]
    s3-access-key-id: ENC[AES256_GCM,data:v95JrJ1L/F5uNLNzmVN5R/rER/iWH8bI5C2FU6hoDSI=,iv:13lYfnvLIucxlrbmrnFLUb+JwIPv8IIt86NogwWVNk4=,tag:eQJ2kewqvzFmQNvyd6Sn6A==,type:str]
    s3-secret-access-key: ENC[AES256_GCM,data:L7pM4myPhZJJLl1pA94gt/zg5EkAOux7BlLuLd4fk1Tyv1h+xCPUEz+G4Nl3ijxc9qR1O7hv+7m8TV5FKsT0mQ==,iv:mXWtzpuyPOOIMXUDNfGo4OqMe9sFeHXJpG+gTQaB1yA=,tag:Cotizbh8RAMdnrsR63sV3A==,type:str]
    s3-region: ENC[AES256_GCM,data:urwfzQ==,iv:3gEQSpNHHwQFbAIV1LxtoYtjOtsTmaa6lqy1ybAwqfU=,tag:zVfg6QxX/h90vlIVErnvgQ==,type:str]
sops:
    age:
        - recipient: age1vk7c2yw7dmmk62vwpns5m8z0ljujkf9xv8ad8ml5qxp97l7mlatq0mq9lf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLWmlacjNJMzhYMGs0L2xI
            WnpQWGNRREFUZTRUbDgrcmhHSFdpSGczb1hJCndyencvU2did1FSSVFNN2orU0ph
            THR6eWY0RnVpekx1TUpiRjJIcGQ4RjQKLS0tIG9wOTUxN1pLSnhEdlVJaTZJODVR
            ZlRtb3pReHplV1JCdjBnM29EZmZWT3MKYNyoUJo94dUq5Bosii8g44F4fpmuX4qD
            qNwQY1Vtg9AqpjUTxGu0GEkSAVV8Dfdsd2pP6/0oEuZEh9GOahaauA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-11T06:36:01Z"
    mac: ENC[AES256_GCM,data:GHajlLYUBqM55VCQ8BgAswOuBoZQgV4f+xRffnwz3PlK3OGH0x6E5RpNYcgXHFbSOkOinuyXNOGO3kmyiA611AaUNyPbKeowZYvJUQ2rNvAJyeRndPoyGZ8BkNNVritt2Qp/uEWY2C7TBXYpqvNZryO75EHzbRWqNEg8qF3ID7g=,iv:H+0bo1lwQMwSj+zPIR7FEjLotZpp5/jn7N67H5PMSZA=,tag:W5Uf2v3pmcnR/OSWZA3gRg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
