apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homestead-pack
  namespace: cozy-friends
  labels:
    app.kubernetes.io/name: homestead
    app.kubernetes.io/part-of: cozy-friends
    app.kubernetes.io/component: pack
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
