apiVersion: v1
kind: Secret
metadata:
    name: company-brain-db-user
    namespace: company-brain
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:ti5WfEwYcIxGkQmmXf/45ZM=,iv:m1lW27lgyc/qKgeIGL+yKlYJ07g9V3ivwcPHiUb0UDA=,tag:xVeVL+hYHeNTGhFszJcjjA==,type:str]
    password: ENC[AES256_GCM,data:17G8RTd9NZWZ9Z8=,iv:qAIxHT8DzEbb7Iw71ejECRr+Gm8MTP1XbwX3Enf3LRA=,tag:3j0fMzUqsbKt48dc1SB4Tw==,type:str]
sops:
    age:
        - recipient: age1vk7c2yw7dmmk62vwpns5m8z0ljujkf9xv8ad8ml5qxp97l7mlatq0mq9lf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXcFFxdjdUY3VXU2xySUxO
            OFZIZGprdER6VUh3dVNZdUpJeTlTV1UvVlM4CkVpVEJsZWptSitJU3Q5VWZkZWVT
            Q1l0RVJXRW9GNkRmYXZScXFtM3BsREkKLS0tIEEzczZEYTJOdGdMcVZpN0djNnM0
            QlpVclhFT2g5a25tV3IzM0pXK3FZVkEK+izzoOm65Tc0vuFK79XyiSMGQ9BpkS1F
            W0VkuoHPcpXNwvxnLJlNV6nLMMJvlFjMUQl730uQK5BG4/tigqKoJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-01T20:11:18Z"
    mac: ENC[AES256_GCM,data:AIdspyGwmDwEVOdT31uEB68shhsKZJ7fm+v9uoNfNrMFDNwDDyeTlz4uwbPd6bIHOa3HhQrdcBHQ+ttbr82mN/KJIPow7KlESyEjuSAeq+IYijFSuWTnYTBp+kPhf07CUWax04NK7UVRfdw3pBJU52sToowIGYrEreKLy4f88dQ=,iv:/JR51sBHBu0R4hM+l7LvQi29RcuW8gyBAh6PWLBeb8s=,tag:4nUSRpmp3XM3WDZfxRdIOQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
