apiVersion: v1
kind: Secret
metadata:
    name: company-brain-db-backup-r2
    namespace: company-brain
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:adZezD2CAW0ejLFLBqFSu2bdSXvUr3O6oWmsOM0YnMg=,iv:DYV5iZI4Raofn6YMa/H+38MWcuhM47KDOce0sTRwLnM=,tag:HziSwJqMK2Pw6avd1FBE6Q==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Jofe8FQ2QjDZfPw4xDLykg08RExED5C8yoP1T2rlOzJaNeg6+HOqVNj/aBKroY+QsTj6s4UquGtyAUyu9/zoMw==,iv:up8CBFIp4H8U1DK/TGukDlbJuXuZwtG7DMj5ErDQ+OU=,tag:Q1cVWvuh0rFVQ9A+MTCBcg==,type:str]
sops:
    age:
        - recipient: age1vk7c2yw7dmmk62vwpns5m8z0ljujkf9xv8ad8ml5qxp97l7mlatq0mq9lf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSc3NEYnJncUx5WWxjOXhC
            ZWxDMVN0RUpIRlQwcmpRYlRZTVJSMzhZdTFjCmljbWJONEc0VUZmR010YytGTmdr
            WVNZd1FnN2NXL0NyYkRBWTh0MTJGT3MKLS0tIHdpWnhqVjVEWUFXTjBqVE5UM1Jx
            OGZ1UkRWRG9nbk9YMWFtZ0xnbkZ4aXcKXTfhIdkcEHWqK1NzhvCS3+l+IXMAuwmJ
            1sjXdMt//orfrE1qq2Tqs2bWHVPNTcy+GN3nitPtqm92Me1gzsPL6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-15T02:45:00Z"
    mac: ENC[AES256_GCM,data:H4MwwFqH5Hg/3X1DgGhMOuB/YbQRCpqVRtKWhLNZTVEPWOi2gS5Ff+8eaA/nN2Cpj4H3+GzlIq3+LVQaIee5LpkenhRPMBseD/sPCe8eXqtn4MYh5ZouW0U7tfH9rmW4kqISMZ/Y3CmRPmpd99hGD/mWBj/gJEB63snbEhmGdEk=,iv:ra74oErw7TWIT0QNIb3H9fEGzwk2LTSgg+R60uCYh2o=,tag:2WELPo33UsHaXwAe2kJJpg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
