apiVersion: v1
kind: Secret
metadata:
    name: whisper-env
    namespace: whisper
type: Opaque
stringData:
    WHISPER_PASSWORD: ENC[AES256_GCM,data:SawR5D42ao+46W8WZTT3f7rMyM/1zZ/J,iv:TLkKAcnB3pLY1KdwIU5xOqU+iir7zOWm9hMGqPIHSmE=,tag:ae0jbrK1pWHI3GSh+0CNsw==,type:str]
    WHISPER_SESSION_SECRET: ENC[AES256_GCM,data:+hS/mGZu6N1ucXBdJdLZ/+01O3OUOpsCeShN2ZKfTpkwS5qIMKZGX/P5FqiZuNRtY4r+TpLcN8HSNDOU1WkILg==,iv:esLcDejR598ViO3rV+k14zdFeDO1HPvI3531/hWoAn8=,tag:gMR8Wk7m7ceeRm1n4Y9zZw==,type:str]
sops:
    age:
        - recipient: age1vk7c2yw7dmmk62vwpns5m8z0ljujkf9xv8ad8ml5qxp97l7mlatq0mq9lf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6S0cwMVRUdFlTa2hQVUxI
            MnhmZDRzWis3YmJmNDBZMUk4bmhzM2lndlRnCk1TbXhORlNnakNDRDVWZ01KUXlt
            MzdzZ1k2VmpJMFgwYUwrVVFIbzhvMmcKLS0tIGljZ2lSb2xaMlNXNUFURk00dHZa
            djBmNFFmVTNkclZTeTlQMTlRV0MxUFUKk7Hti1ic7cKEq7HTy3TCZzA9Rmw8e5fG
            81Ze3JJRICHe6pxcuQLDbUqNOqSuhbDU4is4hWk0rF0k8Tr7IXEFRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-16T19:03:00Z"
    mac: ENC[AES256_GCM,data:DWORCdKcO2BxxSmK+OCogLXWL0Vmk/ynXZRByqxxj9o+h43zCgb64sJoSiUpJzIJBkkrWTd/obed4+KrB8iZ7WakP7mrUtrlIsaS4Lb/D5RMHgZjUmrH5jeodAsZXte3ONuoUpb5yhtIKHcqZzbBDj5F6OCdTLghHjwv9zkIK1Y=,iv:QMQEEuftaCKG/lXzDD/GOkjpix2NA/tUXz++okmjeQU=,tag:eFDpEy7PS5d1Bucj5TPycw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
