apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-token
    namespace: cloudflare-ddns
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:PH79QI2u3kZQdmVHUHvXcftvQ6EbkgcFb+nwMYrLlgSNAsRjpahlG3w0CoM1eJnFQ5nqrNI=,iv:1wbYghrn7lOEI2O0KltVnsZTIG+I4VWiWzDhCbMh1e4=,tag:Ap5hMR7gmn6HYmzEc5qeNg==,type:str]
sops:
    age:
        - recipient: age1vk7c2yw7dmmk62vwpns5m8z0ljujkf9xv8ad8ml5qxp97l7mlatq0mq9lf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXQTRWOVdCQlZNd05vLzJw
            bWdZNll0TVNHNmZLY3BLVFFhVzg4ZGFLVkVzCmdxei9hdnlrNGdLMTYwcExyVCtH
            N010bkx2WncwbmRaWkxOWTkzT0FYMkUKLS0tIFd4Mnh1WjRrTUJIRU1BWU5VVnFC
            OWk0bGxMMnE3RjFWTEcxMllHOUxpTFUK+Sn4+2aGX9Pgpa5n/xPFc0Pi53b4bggS
            N0q1NFCPAygC5wAT8D21DjYoBEiOYgiScggv5kw9UR2HatpjTpyIaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-11T06:18:41Z"
    mac: ENC[AES256_GCM,data:IrcbnRW87w+7y+kEPozxpbC30w1W0zoBINJHSJ/7X544cysoOf5uKPFbScisIThKrFVvFIAtt4NaweAQjPUuMJuUdoFqNIoLynFwQ0agLAlqA9+JOiFnxd4AqVz75HMNE2K/Swt7WMs20iYjEoBVvVCdawcxGrPkWGX00kGiXTs=,iv:/QmptlRgkKdfrB2KIWXup57NmypBZ/MExpM4SV9wcNI=,tag:F0qr66ZqjbzINgu0mJvW5A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
