apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-token
    namespace: cloudflare-ddns
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:4C+lgadJJc54wrx4zdLSi5AbSfTTPbDvQ/5dMd6dNOo=,iv:kLUfnQaYKVNRQfsYEagbrt8V3jzGmRZN24edLZQI/WM=,tag:2IFqJdb50TM6TdmvTnrilg==,type:str]
sops:
    age:
        - recipient: age1vk7c2yw7dmmk62vwpns5m8z0ljujkf9xv8ad8ml5qxp97l7mlatq0mq9lf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXQTRWOVdCQlZNd05vLzJw
            bWdZNll0TVNHNmZLY3BLVFFhVzg4ZGFLVkVzCmdxei9hdnlrNGdLMTYwcExyVCtH
            N010bkx2WncwbmRaWkxOWTkzT0FYMkUKLS0tIFd4Mnh1WjRrTUJIRU1BWU5VVnFC
            OWk0bGxMMnE3RjFWTEcxMllHOUxpTFUK+Sn4+2aGX9Pgpa5n/xPFc0Pi53b4bggS
            N0q1NFCPAygC5wAT8D21DjYoBEiOYgiScggv5kw9UR2HatpjTpyIaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-11T06:16:49Z"
    mac: ENC[AES256_GCM,data:tlBkbqh0+PyWUqSvchussOEGBvlkHzv27FgFcbVTNOIn61m7sg3gkT+rrX/heCQTgiDkjfn9978Th7KGoHCRqapBTDegXBT78NOe0RuJ9hV+mcBJMYqFAGnLiijugHR8coMEFhr73f/W4g1Se8nHRyMVShGtufzl404Ra4V6uu4=,iv:hMY5RFKYg9hZRYLHaD58GneqZKrK4Hb5L3SnYgpohJM=,tag:rVBZKqeZ3J9IgkjDgF0UjQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
