apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        site-version: "2026-04-30-resume-link"
    spec:
      volumes:
        - name: landing-page
          configMap:
            name: nginx-landing-page
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: landing-page
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
            - name: landing-page
              mountPath: /usr/share/nginx/html/styles.css
              subPath: styles.css
            - name: landing-page
              mountPath: /usr/share/nginx/html/Daniel_Cheung_Resume.pdf
              subPath: Daniel_Cheung_Resume.pdf
